### PR TITLE
Knighting registry added

### PR DESCRIPTION
**Pull request by aj-maz**
I have added a simple registry for knighting round

it will deploy an implementation of KnightingRound and an implementation of KnightingRoundWithEth

I will clone that implementation for all expected rounds.

I also have used the main KnightingRound and KnightingRoundWithEth implementations for wEth and Eth for gas efficiency

added 3 view functions for frontend data.

### CODE REVIEW

**Comment by aj-maz** [comment]
should close #103

**Comment by dapp-whisperer** [comment]
solid implementation - I like the simplicity of adding rounds and the extra view functions added (such as `getRoundData`).

This will make setting parameters much easier as well.

**Comment by dapp-whisperer** [comment]
As discussed the cloning method should switch the TransparentUpgradeableProxy

**Comment by aj-maz** [comment]
@dapp-whisperer I have done some research around the solution and I figured out that [Becon Proxies](https://docs.openzeppelin.com/contracts/4.x/api/proxy#BeaconProxy) makes more sense for the factory since we can change all implementations at once with changing the Upgradable Beacon.

But it was raising another issue which was the standard Upgradeable Beacon implementation of Openzepplin was an ownable contract, so I made a custom version of it called GACUpgradableBeacon.sol which is basically the same contract but it works with GlobalAccessControl and CONTRACT_GOVERNANCE_ROLE can upgrade the beacon.

**Comment by aj-maz** [comment]
Changed from Beacon to the Transparent Proxy

The standard ProxyAdmin implementation of Openzepplin was an ownable contract, so I made a custom version of it called GACProxyAdmin.sol which is basically the same contract but it works with GlobalAccessControl and CONTRACT_GOVERNANCE_ROLE is the same as what the owner is to ProxyAdmin.

**Comment by sajanrajdev** [comment]
@Ajand, would you mind merging the changes from `main` and run the linter with `npm run prettier:solidity` so that the linting issues get fixed? 

The test action is expected to fail as the PR is openned from a forked repo and the main repo's ALCHEMY_KEY  can't be used. Since the PR doesn't touch any of the tests nor the other contracts I don't see why any of these would be broken. Although an Screenshot of the tests passing locally for you would be great for reassurance.

**Comment by sajanrajdev** [comment]
@Ajand, seems to me like these changes have already been included on https://github.com/Citadel-DAO/citadel-contracts/pull/165, are we good to close?

**Comment by aj-maz** [comment]
@sajanrajdev sure

**Pull request closed without merging**
