### PR TITLE
Test/locking updates

### PR DESCRIPTION
**Pull request by Fatimanaz**
Added tests for cumulativeDistributed and cumulativeClaimed
https://github.com/Citadel-DAO/citadel-contracts/issues/132

### CODE REVIEW

**Review by sajanrajdev — APPROVED** [review]
Tests the newly introduced `getCumulativeClaimedRewards` and `cumulativeDistributed` functions within the Locker integration flows. LGTM.

Note: `npm run solhint` is not throwing any Errors locally but it is failing in CI, needs further investigation:
image

**Comment by sajanrajdev** [comment]
Lint passing locally is due to the latest changes to the Linter scripts not being merged to the branch. These fixes included broadering the scope of the linter. @Fatimanaz merging the latest changes from `main` and re-running the formatter should get CI to pass.

**Comment by Fatimanaz** [comment]
I updated the PR now all CI tests are passed.

**Review by sajanrajdev — APPROVED** [review]
Changes LGTM, mainly linting fixes.

**Review by dapp-whisperer — APPROVED** [review]

**Pull request merged**
