### PR TITLE
Knighting round eth

### LINKED ISSUE #77: Develop KnightingRound variant to take in ETH
## Premise
The KnightingRounds are designed to take in arbitrary ERC20s.
To maintain compatibility, we'll take in WETH as the asset here.

However, we'd like users to be able to deposit ETH directly.

## The Task
* create a buyEth() function variant that is payable, and deposits the ETH into WETH before calling the current buy() function and forwards along all the needed parameters.

* create test cases for this new KnightingRound confirming the buyEth() flow works

I'd recommend this new KnightingRound contract inherit from the current KnightingRound contract rather than duplicating logic.

### PR DESCRIPTION
**Pull request by shinji2048**

### CODE REVIEW

**Comment by dapp-whisperer** [comment]
image
@Darruma @sajanrajdev do you know why this test is failing?

**Comment by shinji2048** [comment]
> image
> 
> @Darruma @sajanrajdev do you know why this test is failing?

For some reason minting weth with the erc20.forceMint doesn't seem to work. Workaround is to mint eth to the address then manually deposit in to the weth contract

**Comment by sajanrajdev** [comment]
- Added pausing tests on the GAC suite
- Added guestlist tests for this KnightingRound contract

**Review by sajanrajdev — APPROVED** [review]
Introduces a variation of the Knighting Round contract that allows deposits with native ETH. A new test suite was introduced that mimics that of the original Knighting Round (wBTC) but adjusting it to the new buyEth call.

LGTM

**Pull request merged**
